language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-source --dev

script:
  - composer test --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - 2.x