cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 7.4.0

before_script:
  - composer install --no-interaction --no-suggest --prefer-source --dev
  - composer require "nyholm/psr7:^1.2" "php-coveralls/php-coveralls:^2.2"

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - vendor/bin/php-coveralls --coverage_clover=clover.xml -v

branches:
  only:
    - 2.x
