language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-source --dev
  - travis_retry composer require "nyholm/psr7:^1.2"

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - 2.x